WINDOW_SIZE = WIDTH, HEIGHT = (800, 600)
FONT_SIZE = 12
FPS = 60

#Cards
CARD_SIZE = CARD_WIDTH, CARD_HEIGHT = (55, 75)
CARD_MARGIN = 5

#Card Lines
MAX_CARD_CHAR = int(CARD_WIDTH / (FONT_SIZE / 1.8))
GAP_BETWEEN_LINES = FONT_SIZE / 5

#Board
BOARD_SIZE = BOARD_WIDTH, BOARD_HEIGHT = (WIDTH / 4 * 2.5, HEIGHT)
NB_CARD_PER_LINE = int(BOARD_WIDTH / (CARD_WIDTH + CARD_MARGIN))

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)